version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # Clone the repository
      - run: npm install  # Install dependencies
      - run: npm run build  # Build the Angular app

  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test  # Run tests

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run: echo "Deploying the app..."  # Modify this for actual deployment

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
