version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.19  # Ensures Angular's required Node.js version

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run:
          name: Install Chrome
          command: |
            sudo apt update
            sudo apt install -y wget
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt update
            sudo apt install -y google-chrome-stable
      - run:
          name: Run Tests
          command: npm test

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run: echo "Deploying the app..."  # Modify for actual deployment

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
